<?php
$listarray = array ( array ( 'label' => 'Barcode',
                             'name' => 'barcode',      
                             'width' => 100, 
                             'type' => 'text',
							 'schnellerfass' => 'key',
                             'dbfield' => 'fldbarcode' ),
                     array ( 'label' => 'Artikel',
                             'name' => 'artikel', 
                             'width' => 50, 
							 'fieldsave' => 'NO',
                             'type' => 'selectshow',
                             'dbtable' => 'tblartikel',
                             'seldbfield' => 'fldbarcode',
                             'selfield' => 'fldbarcode',
							 'seldbbez' => 'fldBez',
                             'dbfield' => 'flddummy' ),
                     array ( 'label' => 'Ort (kurz)',
                             'name' => 'ortkurz', 
                             'getdefault' => 'true',
                             'width' => 5, 
                             'type' => 'text',
							 'schnellerfass' => 'ort',
                             'dbfield' => 'fldortkurz' ),
                     array ( 'label' => 'Ort',
                             'name' => 'ortbez', 
                             'width' => 50, 
							 'fieldsave' => 'NO',
                             'type' => 'selectshow',
                             'dbtable' => 'tblortkurz',
                             'seldbfield' => 'fldkurz',
                             'selfield' => 'fldortkurz',
							 'seldbbez' => 'fldbez',
                             'dbfield' => 'flddummy1' ),
                     array ( 'label' => 'Anz',
                             'name' => 'anz',      
                             'width' => 20, 
                             'type' => 'text',
							 'schnellerfass' => 'anz',
                             'dbfield' => 'fldanz' ),
                     array ( 'label' => 'ME',
                             'name' => 'mengein', 
                             'width' => 50, 
							 'fieldsave' => 'NO',
                             'type' => 'selectshow',
                             'dbtable' => 'tblartikel',
                             'seldbfield' => 'fldbarcode',
                             'selfield' => 'fldbarcode',
							 'seldbbez' => 'fldverpackbez',
                             'dbfield' => 'flddummy2' ),
                     array ( 'label' => 'Mind.halt.-Datum',
                             'name' => 'mhdatum',      
                             'width' => 20, 
                             'type' => 'date',
                             'dbfield' => 'fldmhdatum' ));

/*
$filterarray = array ( array ( 'label' => 'Artikel:',
                               'name' => 'fltartikel', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblartikel',
                               'seldbfield' => 'fldbarcode',
                               'dbfield' => 'fldbarcode' ),
                       array ( 'label' => 'Von Ort:',
                               'name' => 'fltvonortkurz', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '>=',
                               'dbtable' => 'tblortkurz',
                               'seldbfield' => 'fldkurz',
                               'dbfield' => 'fldortkurz' ),
                       array ( 'label' => 'Bis Ort:',
                               'name' => 'fltbisortkurz', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '<=',
                               'dbtable' => 'tblortkurz',
                               'seldbfield' => 'fldkurz',
                               'dbfield' => 'fldortkurz' ));							 
*/

$pararray = array ( 'headline' => 'Vorrat',
                    'dbtable' => 'tblvorrat',
                    'orderby' => 'fldortkurz,fldbarcode',
                    'strwhere' => '',
                    'markseldb' => 'J',
                    'markseltyp' => 'date',
                    'fldindex' => 'fldindex');

?>