<?php

$listarray = array ( array ( 'label' => 'Nr',
                             'width' => 10, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'Konto',
                             'name' => 'konto', 
                             'getdefault' => 'true',
                             'width' => 5, 
                             'type' => 'select',
                             'dbtable' => 'tblktokonten',
                             'seldbfield' => 'fldKurz',
                             'dbfield' => 'fldKonto' ),
                     array ( 'label' => 'Preis',
                             'name' => 'preis', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldPreis' ),
                     array ( 'label' => 'Anz',
                             'name' => 'anz', 
                             'width' => 100, 
                             'type' => 'text',
                             'default' => '1',
                             'dbfield' => 'fldAnz' ),
                     array ( 'label' => 'JN',
                             'name' => 'jn', 
                             'width' => 10, 
                             'type' => 'text',
                             'default' => 'J',
                             'dbfield' => 'fldJN' ),
                     array ( 'label' => 'Ort',
                             'name' => 'ort', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldOrt' ));

$filterarray = array ( 
                       array ( 'label' => ' Kaufort:',
                               'name' => 'kaufort', 
                               'addfunc' => 'true',
                               'funcsetbutton' => 'true',
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblorte',
                               'seldbwhere' => "fldo01typ='FREMD'",
                               'seldbfield' => 'fldBez',
                               'dbfield' => 'fldort' ));


$pararray = array ( 'headline' => 'Stammdaten',
                    'dbtable' => 'tblartikel',
                    'addfunc' => 'true',
                    'fldarchivdat' => 'fldArchivDat',
                    'orderby' => 'fldOrt, fldBez',
                    'strwhere' => "fldArchivDat=''",
                    'fldindex' => 'fldindex',
                    'fldbez' => 'fldBez',
                    'fldEinkaufDat' => 'fldEinkaufDat',
                    'strort' => 'J',
                    'markbgcolor' => '88ff88',
                    'ummarkbgcolor' => 'ffffff',
                    'marksuccess' => 'OK',
                    'marksign' => '=',
                    'markfield' => 'fldStatus');

?>