<?php

$listarray = array ( array ( 'label' => 'Nr',
                             'width' => 10, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'Preis',
                             'name' => 'preis', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldPreis' ),
                     array ( 'label' => 'Anz',
                             'name' => 'anz', 
                             'width' => 100, 
                             'type' => 'text',
                             'default' => '1',
                             'dbfield' => 'fldAnz' ),
                     array ( 'label' => 'JN',
                             'name' => 'jn', 
                             'width' => 10, 
                             'type' => 'text',
                             'default' => 'J',
                             'dbfield' => 'fldJN' ),
                     array ( 'label' => 'Ort',
                             'name' => 'ort', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldOrt' ));


$pararray = array ( 'headline' => 'Stammdaten',
                    'dbtable' => 'tblartikel',
                    'addfunc' => 'true',
                    'fldarchivdat' => 'fldArchivDat',
                    'orderby' => 'fldOrt, fldBez',
                    'strwhere' => "fldArchivDat=''",
                    'fldindex' => 'fldindex',
                    'fldbez' => 'fldBez',
                    'fldEinkaufDat' => 'fldEinkaufDat',
                    'strort' => 'J',
                    'markbgcolor' => '88ff88',
                    'ummarkbgcolor' => 'ffffff',
                    'marksuccess' => 'OK',
                    'marksign' => '=',
                    'markfield' => 'fldStatus');

?>