<?php
$listarray = array ( 
                     array ( 'label' => 'ID',
                             'fieldsave' => 'NO',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldindex' ),
                     array ( 'label' => 'Datum',
                             'name' => 'datum',
                             'width' => 100, 
                             'type' => 'date',
                             'default' => 'now()',
                             'dbfield' => 'fldDatum' ),
                     array ( 'label' => 'Uhrzeit',
                             'name' => 'uhrzeit',
                             'width' => 100, 
                             'type' => 'time',
                             'default' => 'now()',
                             'dbfield' => 'fldUhrzeit' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'Konto',
                             'name' => 'konto', 
                             'getdefault' => 'true',
                             'width' => 5, 
                             'type' => 'select',
                             'dbtable' => 'tblktokonten',
                             'seldbfield' => 'fldKurz',
                             'dbfield' => 'fldKonto' ),
                     array ( 'label' => 'Kontoinhaber',
                             'name' => 'kontoinhaber', 
                             'getdefault' => 'true',
                             'width' => 5, 
                             'type' => 'select',
                             'dbtable' => 'tblktoinhaber',
                             'seldbfield' => 'fldBez',
                             'fieldhide' => 'true1',
                             'dbfield' => 'fldInhaber' ),
                     array ( 'label' => 'Betrag',
                             'name' => 'betrag',
                             'width' => 100, 
                             'type' => 'calc',
                             'dbfield' => 'fldBetrag' ),
                     array ( 'label' => 'Bar',
                             'name' => 'bar',
                             'width' => 100, 
                             'type' => 'calcsum',
                             'dbfield' => 'fldBetrag' ),
                     array ( 'label' => 'timestamp',
                             'name' => 'timestamp',
                             'fieldhide' => 'true1',
                             'fieldsave' => 'NO',
                             'width' => 100, 
                             'type' => 'timestamp',
                             'dbfield' => 'fldtimestamp' ),
                     array ( 'label' => 'SyncNr',
                             'name' => 'syncnr',
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'flddbsyncnr' ),
                     array ( 'label' => 'Sync',
                             'name' => 'dbsync',
                             'default' => 'SYNC',
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'flddbsyncstatus' ),
                     array ( 'label' => 'Fix',
                             'name' => 'fix',
                             'fieldhide' => 'true',
                             'width' => 70, 
                             'type' => 'zahl',
                             'dbfield' => 'fldFix' ));

$filterarray = array ( array ( 'label' => 'Kontoinhaber:',
                               'name' => 'fltkontoinhaber', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblktoinhaber',
                               'seldbfield' => 'fldBez',
                               'dbfield' => 'fldInhaber' ),
                       array ( 'label' => 'ab Datum:',
                               'name' => 'zeitraumvon',
                               'value' => '', 
                               'width' => 500, 
                               'type' => 'date',
                               'sign' => '>=',                              
                               'dbfield' => 'fldDatum' ),
                       array ( 'label' => 'bis Datum:',
                               'name' => 'zeitraumbis',
                               'value' => '', 
                               'width' => 500, 
                               'type' => 'date',
                               'sign' => '<=',                              
                               'dbfield' => 'fldDatum' ),
                       array ( 'label' => ' Konto:',
                               'name' => 'fltkonto', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblktokonten',
                               'seldbfield' => 'fldKurz',
                               'dbfield' => 'fldKonto' ));

$pararray = array ( 'headline' => 'Buchführung',
                    'dbtable' => 'tblktosal',
                    'orderby' => 'fldDatum,fldUhrzeit',
                    'dbwhere' => "flddel='N'",
                    'dbsyncnr' => 'J',
                    'dellogical' => 'J',
                    'calcsum' => 'J',
                    'markseldb' => 'J',
                    'fldindex' => 'fldindex');
?>