<?php
$listarray = array ( array ( 'label' => 'Datum',
                             'name' => 'datum',
                             'width' => 50, 
                             'type' => 'date',
                             'dbfield' => 'flddatum' ),
                     array ( 'label' => 'Fahrzeug',
                             'name' => 'fahrzeug',
                             'width' => 150, 
                             'type' => 'text',
                             'dbfield' => 'fldfahrzeug' ),
                     array ( 'label' => 'Zeitpreis',
                             'name' => 'zeitpreis',
                             'width' => 10, 
                             'type' => 'text',
                             'fieldhide' => 'true',
                             'dbfield' => 'fldzeitpreis' ),
                     array ( 'label' => 'Dauer',
                             'name' => 'dauer',
                             'width' => 20, 
                             'type' => 'text',
                             'prenumber' => 1,
                             'dbfield' => 'flddauer' ),
                     array ( 'label' => 'Von  km',
                             'name' => 'vonkm',
                             'width' => 20, 
                             'type' => 'text',
                             'prenumber' => '0',
                             'dbfield' => 'fldvonkm' ),
                     array ( 'label' => 'Bis km',
                             'name' => 'biskm',
                             'width' => 20, 
                             'type' => 'text',
                             'prenumber' => '0',
                             'dbfield' => 'fldbiskm' ),
                     array ( 'label' => 'Anz km',
                             'name' => 'anzkm',
                             'width' => 20, 
                             'type' => 'calcdiff',
                             'calcfield' => 'fldvonkm',
                             'fieldsave' => 'NO',
                             'dbfield' => 'fldbiskm' ),
                     array ( 'label' => 'Km-Preis',
                             'name' => 'kmpreis',
                             'width' => 20, 
                             'type' => 'calcdiffsum',
                             'calcfix' => '0.26',
                             'calcfield' => 'fldvonkm',
                             'fieldsave' => 'NO',
                             'dbfield' => 'fldbiskm' ),
                     array ( 'label' => 'Zeitpreis',
                             'name' => 'zeitpreis', 
                             'width' => 10, 
                             'type' => 'calc',
                             'calcfield' => 'fldzeitpreis',
                             'fieldsave' => 'NO',
                             'dbfield' => 'flddauer' ),
                     array ( 'label' => 'Gesamtpreis',
                             'name' => 'gesamtpreis',
                             'width' => 20, 
                             'type' => 'calcaddsum',
                             'calcadddbfield' => 'fldzeitpreis',
                             'calcaddfield' => 'flddauer',
                             'calcfix' => '0.26',
                             'calcfield' => 'fldvonkm',
                             'fieldsave' => 'NO',
                             'dbfield' => 'fldbiskm' ),
                     array ( 'label' => 'Status',
                             'name' => 'status',
                             'fieldhide' => 'true1',
                             'width' => 20, 
                             'type' => 'select',
                             'dbtable' => 'tblstatus',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldStatus' ));

$filterarray = array ( array ( 'label' => 'Status:',
                               'name' => 'status', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblstatus',
                               'seldbfield' => 'fldbez',
                               'dbfield' => 'fldStatus' ));


$pararray = array ( 'headline' => 'Fahrtenbuch',
                    'dbtable' => 'tblfahrtenbuch',
                    'orderby' => 'flddatum desc,fldfahrzeug',
                    'strwhere' => '',
                    'marktype' => 'text',
                    'markbgcolor' => '22ff22',
                    'markfield' => 'fldStatus',
                    'marksign' => '=',
                    'marksuccess' => 'OK',
                    'fldindex' => 'fldIndex');
?>