<?php
$tablearray = array ( array('tablename' => 'sqlite_sequence',
'sql' => 'CREATE TABLE sqlite_sequence(name,seq)',
'column' => array('name','seq')),
array('tablename' => 'tblfilter',
'sql' => 'CREATE TABLE tblfilter (fldtablename TEXT, fldwert TEXT, fldfeld TEXT, fldindex INTEGER PRIMARY KEY)',
'column' => array('fldtablename TEXT',' fldwert TEXT',' fldfeld TEXT',' fldindex INTEGER PRIMARY KEY')),
array('tablename' => 'tblkategorie',
'sql' => 'CREATE TABLE tblkategorie (fldindex INTEGER PRIMARY KEY, fldbez TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY',' fldbez TEXT')),
array('tablename' => 'tblktokonten',
'sql' => 'CREATE TABLE tblktokonten (fldindex INTEGER PRIMARY KEY AUTOINCREMENT, fldKurz TEXT, fldBez TEXT, fldTyp TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY AUTOINCREMENT',' fldKurz TEXT',' fldBez TEXT',' fldTyp TEXT')),
array('tablename' => 'tblEinkauf_liste',
'sql' => 'CREATE TABLE tblEinkauf_liste (fldKonto TEXT, fldStatus TEXT, fldArchivDat TEXT, fldEinkaufDatum TEXT, fldOrt TEXT, fldPreis TEXT, fldAnz TEXT, fldindex INTEGER PRIMARY KEY, fldBez TEXT)',
'column' => array('fldKonto TEXT',' fldStatus TEXT',' fldArchivDat TEXT',' fldEinkaufDatum TEXT',' fldOrt TEXT',' fldPreis TEXT',' fldAnz TEXT',' fldindex INTEGER PRIMARY KEY',' fldBez TEXT')),
array('tablename' => 'tblktoinhaber',
'sql' => 'CREATE TABLE tblktoinhaber (flindex INTEGER PRIMARY KEY AUTOINCREMENT, fldBez TEXT)',
'column' => array('flindex INTEGER PRIMARY KEY AUTOINCREMENT',' fldBez TEXT')),
array('tablename' => 'tblktosal',
'sql' => 'CREATE TABLE tblktosal (fldindex INTEGER PRIMARY KEY, fldDatum TEXT, fldUhrzeit TEXT, fldBez TEXT, fldKonto TEXT, fldInhaber TEXT, fldBetrag TEXT, fldFix NUMERIC, "fldtyp" text NULL)',
'column' => array('fldindex INTEGER PRIMARY KEY',' fldDatum TEXT',' fldUhrzeit TEXT',' fldBez TEXT',' fldKonto TEXT',' fldInhaber TEXT',' fldBetrag TEXT',' fldFix NUMERIC',' "fldtyp" text NULL')),
array('tablename' => 'tblversion',
'sql' => 'CREATE TABLE tblversion (fldindex INTEGER PRIMARY KEY, fldbez TEXT, fldversion TEXT, flddatum TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY',' fldbez TEXT',' fldversion TEXT',' flddatum TEXT')),
array('tablename' => 'tblprior',
'sql' => 'CREATE TABLE tblprior (fldindex INTEGER PRIMARY KEY AUTOINCREMENT, fldprior TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY AUTOINCREMENT',' fldprior TEXT')),
array('tablename' => 'tblerledigungen',
'sql' => 'CREATE TABLE tblerledigungen (fldprior TEXT, fldErledigDat TEXT, fldDatum TEXT, fldcategory TEXT, fldindex INTEGER PRIMARY KEY, fldbez TEXT, fldstatus TEXT)',
'column' => array('fldprior TEXT',' fldErledigDat TEXT',' fldDatum TEXT',' fldcategory TEXT',' fldindex INTEGER PRIMARY KEY',' fldbez TEXT',' fldstatus TEXT')),
array('tablename' => 'tblmenu_liste',
'sql' => 'CREATE TABLE tblmenu_liste (fldid_parent NUMERIC, fldglyphicon TEXT, fldlink TEXT, fldsort TEXT, fldbez TEXT, fldindex INTEGER PRIMARY KEY, fldmenu TEXT, fldview TEXT)',
'column' => array('fldid_parent NUMERIC',' fldglyphicon TEXT',' fldlink TEXT',' fldsort TEXT',' fldbez TEXT',' fldindex INTEGER PRIMARY KEY',' fldmenu TEXT',' fldview TEXT')),
array('tablename' => 'tblartikel',
'sql' => 'CREATE TABLE tblartikel (fldKonto TEXT, fldJN TEXT, fldAnz TEXT, fldindex INTEGER PRIMARY KEY, fldBez TEXT, fldPreis TEXT, fldOrt TEXT)',
'column' => array('fldKonto TEXT',' fldJN TEXT',' fldAnz TEXT',' fldindex INTEGER PRIMARY KEY',' fldBez TEXT',' fldPreis TEXT',' fldOrt TEXT')),
array('tablename' => 'tblstatus',
'sql' => 'CREATE TABLE tblstatus (fldtyp TEXT, fldindex INTEGER PRIMARY KEY, fldbez TEXT)',
'column' => array('fldtyp TEXT',' fldindex INTEGER PRIMARY KEY',' fldbez TEXT')),
array('tablename' => 'android_metadata',
'sql' => 'CREATE TABLE android_metadata (locale TEXT)',
'column' => array('locale TEXT')),
array('tablename' => 'tblfahrtenbuch',
'sql' => 'CREATE TABLE tblfahrtenbuch (fldind_datum TEXT, fldid_adr NUMERIC, fldStatus TEXT, fldindex INTEGER PRIMARY KEY, fldVondatum TEXT, fldVonkm TEXT, fldBiskm TEXT, fldFahrzeug TEXT, fldZeittarif TEXT, fldDauer TEXT)',
'column' => array('fldind_datum TEXT',' fldid_adr NUMERIC',' fldStatus TEXT',' fldindex INTEGER PRIMARY KEY',' fldVondatum TEXT',' fldVonkm TEXT',' fldBiskm TEXT',' fldFahrzeug TEXT',' fldZeittarif TEXT',' fldDauer TEXT')),
array('tablename' => 'tblfunc',
'sql' => 'CREATE TABLE tblfunc (fldindex INTEGER PRIMARY KEY, fldBez TEXT, fldphp TEXT, fldMenuID TEXT, fldTyp TEXT, fldTarget TEXT, fldParam TEXT, fldAktiv TEXT, fldName TEXT, fldtimestamp TEXT, fldversion TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY',' fldBez TEXT',' fldphp TEXT',' fldMenuID TEXT',' fldTyp TEXT',' fldTarget TEXT',' fldParam TEXT',' fldAktiv TEXT',' fldName TEXT',' fldtimestamp TEXT',' fldversion TEXT')),
array('tablename' => 'tblktotyp',
'sql' => 'CREATE TABLE tblktotyp (fldtyp TEXT, fldindex INTEGER PRIMARY KEY, fldbez TEXT)',
'column' => array('fldtyp TEXT',' fldindex INTEGER PRIMARY KEY',' fldbez TEXT')),
array('tablename' => 'tblorte',
'sql' => 'CREATE TABLE tblorte (fldkurz TEXT, fldid_moebel NUMERIC, fldproz NUMERIC, fldid_etage NUMERIC, fldhoehe NUMERIC, fldbreite NUMERIC, fldykoor NUMERIC, fldxkoor NUMERIC, fldview TEXT, fldid_zimmer NUMERIC, fldindex INTEGER PRIMARY KEY, fldBez TEXT, fldo01typ TEXT)',
'column' => array('fldkurz TEXT',' fldid_moebel NUMERIC',' fldproz NUMERIC',' fldid_etage NUMERIC',' fldhoehe NUMERIC',' fldbreite NUMERIC',' fldykoor NUMERIC',' fldxkoor NUMERIC',' fldview TEXT',' fldid_zimmer NUMERIC',' fldindex INTEGER PRIMARY KEY',' fldBez TEXT',' fldo01typ TEXT')),
array('tablename' => 'tbletagen',
'sql' => 'CREATE TABLE tbletagen (fldproz TEXT, fldindex INTEGER PRIMARY KEY, fldbez TEXT)',
'column' => array('fldproz TEXT',' fldindex INTEGER PRIMARY KEY',' fldbez TEXT')),
array('tablename' => 'tblbenutzer',
'sql' => 'CREATE TABLE tblbenutzer (fldindex INTEGER PRIMARY KEY AUTOINCREMENT, fldbez TEXT, fldbackgroundfilename TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY AUTOINCREMENT',' fldbez TEXT',' fldbackgroundfilename TEXT')),
array('tablename' => 'tblsuchobj',
'sql' => 'CREATE TABLE tblsuchobj (fldid_user NUMERIC, fldindex INTEGER PRIMARY KEY, fldbez TEXT)',
'column' => array('fldid_user NUMERIC',' fldindex INTEGER PRIMARY KEY',' fldbez TEXT')),
array('tablename' => 'tblrefsuchobj',
'sql' => 'CREATE TABLE tblrefsuchobj (fldid_zimmer NUMERIC, fldid_moebel NUMERIC, fldtyp TEXT, fldid_orte NUMERIC, fldproz NUMERIC, fldindex INTEGER PRIMARY KEY, fldid_suchobj NUMERIC, fldid_etage NUMERIC)',
'column' => array('fldid_zimmer NUMERIC',' fldid_moebel NUMERIC',' fldtyp TEXT',' fldid_orte NUMERIC',' fldproz NUMERIC',' fldindex INTEGER PRIMARY KEY',' fldid_suchobj NUMERIC',' fldid_etage NUMERIC')),
array('tablename' => 'tblktostamm',
'sql' => 'CREATE TABLE tblktostamm (fldindex INTEGER PRIMARY KEY, fldDatum TEXT, fldUhrzeit TEXT, fldBez TEXT, fldKonto TEXT, fldInhaber TEXT, fldBetrag TEXT, fldFix NUMERIC)',
'column' => array('fldindex INTEGER PRIMARY KEY',' fldDatum TEXT',' fldUhrzeit TEXT',' fldBez TEXT',' fldKonto TEXT',' fldInhaber TEXT',' fldBetrag TEXT',' fldFix NUMERIC')),
array('tablename' => 'tblsession',
'sql' => 'CREATE TABLE "tblsession" (
  "fldindex" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  "fldid" integer NOT NULL
)',
'column' => array('
  "fldindex" integer NOT NULL PRIMARY KEY AUTOINCREMENT','
  "fldid" integer NOT NULL
')),
);
?>