<?php
$tablearray = array ( array('tablename' => 'sqlite_sequence',
'sql' => 'CREATE TABLE sqlite_sequence(name,seq)',
'column' => array('name','seq')),
array('tablename' => 'tblorte',
'sql' => 'CREATE TABLE tblorte (fldindex INTEGER PRIMARY KEY, fldBez TEXT, fldo01typ TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY',' fldBez TEXT',' fldo01typ TEXT')),
array('tablename' => 'tblstatus',
'sql' => 'CREATE TABLE tblstatus (fldindex INTEGER PRIMARY KEY AUTOINCREMENT, fldbez TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY AUTOINCREMENT',' fldbez TEXT')),
array('tablename' => 'tblfilter',
'sql' => 'CREATE TABLE tblfilter (fldtablename TEXT, fldwert TEXT, fldfeld TEXT, fldindex INTEGER PRIMARY KEY)',
'column' => array('fldtablename TEXT',' fldwert TEXT',' fldfeld TEXT',' fldindex INTEGER PRIMARY KEY')),
array('tablename' => 'tblartikel',
'sql' => 'CREATE TABLE tblartikel (fldJN TEXT DEFAULT "J", fldAnz TEXT, fldindex INTEGER PRIMARY KEY, fldBez TEXT, fldPreis TEXT, fldOrt TEXT)',
'column' => array('fldJN TEXT DEFAULT "J"',' fldAnz TEXT',' fldindex INTEGER PRIMARY KEY',' fldBez TEXT',' fldPreis TEXT',' fldOrt TEXT')),
array('tablename' => 'tblkategorie',
'sql' => 'CREATE TABLE tblkategorie (fldindex INTEGER PRIMARY KEY, fldbez TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY',' fldbez TEXT')),
array('tablename' => 'tblktokonten',
'sql' => 'CREATE TABLE tblktokonten (fldindex INTEGER PRIMARY KEY AUTOINCREMENT, fldKurz TEXT, fldBez TEXT, fldTyp TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY AUTOINCREMENT',' fldKurz TEXT',' fldBez TEXT',' fldTyp TEXT')),
array('tablename' => 'tblfahrtenbuch',
'sql' => 'CREATE TABLE tblfahrtenbuch (fldStatus TEXT, fldindex INTEGER PRIMARY KEY, flddatum TEXT, fldvonkm TEXT, fldbiskm TEXT, fldfahrzeug TEXT, fldzeitpreis TEXT, flddauer TEXT)',
'column' => array('fldStatus TEXT',' fldindex INTEGER PRIMARY KEY',' flddatum TEXT',' fldvonkm TEXT',' fldbiskm TEXT',' fldfahrzeug TEXT',' fldzeitpreis TEXT',' flddauer TEXT')),
array('tablename' => 'tblEinkauf_liste',
'sql' => 'CREATE TABLE tblEinkauf_liste (fldKonto TEXT, fldStatus TEXT, fldArchivDat TEXT, fldEinkaufDatum TEXT, fldOrt TEXT, fldPreis TEXT, fldAnz TEXT, fldindex INTEGER PRIMARY KEY, fldBez TEXT)',
'column' => array('fldKonto TEXT',' fldStatus TEXT',' fldArchivDat TEXT',' fldEinkaufDatum TEXT',' fldOrt TEXT',' fldPreis TEXT',' fldAnz TEXT',' fldindex INTEGER PRIMARY KEY',' fldBez TEXT')),
array('tablename' => 'tblktoinhaber',
'sql' => 'CREATE TABLE tblktoinhaber (flindex INTEGER PRIMARY KEY AUTOINCREMENT, fldBez TEXT)',
'column' => array('flindex INTEGER PRIMARY KEY AUTOINCREMENT',' fldBez TEXT')),
array('tablename' => 'tblktosal',
'sql' => 'CREATE TABLE tblktosal (fldindex INTEGER PRIMARY KEY, fldDatum TEXT, fldUhrzeit TEXT, fldBez TEXT, fldKonto TEXT, fldInhaber TEXT, fldBetrag TEXT, fldFix NUMERIC)',
'column' => array('fldindex INTEGER PRIMARY KEY',' fldDatum TEXT',' fldUhrzeit TEXT',' fldBez TEXT',' fldKonto TEXT',' fldInhaber TEXT',' fldBetrag TEXT',' fldFix NUMERIC')),
array('tablename' => 'tblversion',
'sql' => 'CREATE TABLE tblversion (fldindex INTEGER PRIMARY KEY, fldbez TEXT, fldversion TEXT, flddatum TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY',' fldbez TEXT',' fldversion TEXT',' flddatum TEXT')),
array('tablename' => 'tblprior',
'sql' => 'CREATE TABLE tblprior (fldindex INTEGER PRIMARY KEY AUTOINCREMENT, fldprior TEXT)',
'column' => array('fldindex INTEGER PRIMARY KEY AUTOINCREMENT',' fldprior TEXT')),
array('tablename' => 'tblerledigungen',
'sql' => 'CREATE TABLE tblerledigungen (fldprior TEXT, fldErledigDat TEXT, fldDatum TEXT, fldcategory TEXT, fldindex INTEGER PRIMARY KEY, fldbez TEXT, fldstatus TEXT)',
'column' => array('fldprior TEXT',' fldErledigDat TEXT',' fldDatum TEXT',' fldcategory TEXT',' fldindex INTEGER PRIMARY KEY',' fldbez TEXT',' fldstatus TEXT')),
array('tablename' => 'tblmenu_liste',
'sql' => 'CREATE TABLE tblmenu_liste (fldglyphicon TEXT, fldlink TEXT, fldsort TEXT, fldbez TEXT, fldindex INTEGER PRIMARY KEY, fldmenu TEXT, fldview TEXT)',
'column' => array('fldglyphicon TEXT',' fldlink TEXT',' fldsort TEXT',' fldbez TEXT',' fldindex INTEGER PRIMARY KEY',' fldmenu TEXT',' fldview TEXT')),
);
?>