<?php

$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'Bezeichung',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'Kurz',
                             'name' => 'kurz',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldkurz' ),
                     array ( 'label' => 'Etage',
                             'name' => 'etage',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldindex',
                             'seldbwhere' => 'fldo01typ="ETAGEN"',
                             'dbfield' => 'fldid_etage' ),
                     array ( 'label' => 'Zimmer',
                             'name' => 'zimmer',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldindex',
                             'seldbwhere' => 'fldo01typ="ZIMMER"',
                             'dbfield' => 'fldid_zimmer' ),
                     array ( 'label' => 'Anzeigen',
                             'name' => 'anzeigen',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldview' ),
                     array ( 'label' => 'X-Koor',
                             'name' => 'xkoor',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldxkoor' ),
                     array ( 'label' => 'Y-Koor',
                             'name' => 'ykoor',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldykoor' ),
                     array ( 'label' => 'Breite',
                             'name' => 'breite',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldbreite' ),
                     array ( 'label' => 'Höhe',
                             'name' => 'hoehe',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldhoehe' ),
                     array ( 'label' => 'Proz',
                             'name' => 'proz',
                             'width' => 200, 
//                             'type' => 'prozref',
                             'type' => 'proz',
                             'roomid' => 'fldid_orte',
                             'dbfield' => 'fldproz' ),
                       array ( 'label' => 'Gesuchtes:',
                               'name' => 'gesuchtes', 
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tblsuchobj',
                               'seldbindex' => 'fldindex',
                               'seldbfield' => 'fldbez',
                               'dbfield' => 'fldid_suchobj' ),
                     array ( 'label' => 'Typ',
                             'name' => 'Typ',
                             'default' => 'MOEBEL',
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldo01typ' ),
                     array ( 'label' => 'Z',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'showtab.php?menu=zimmer',
                             'dbfield' => 'icon-book' ),
                     array ( 'label' => 'F',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'showtab.php?menu=faecher',
                             'dbfield' => 'icon-book' ));

$filterarray = array ( array ( 'label' => 'Etage:',
                               'name' => 'etage', 
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'onchange' => 'yes',
                               'auswahl' => 'ETAGEN',
                               'dbtable' => 'tblorte',
                               'seldbindex' => 'fldindex',
                               'seldbfield' => 'fldBez',
                               'seldbwhere' => 'fldo01typ="ETAGEN"',
                               'dbfield' => 'fldid_etage' ),
                       array ( 'label' => 'Zimmer:',
                               'name' => 'fltzimmer', 
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'idwhere' => 'ETAGEN',
                               'dbtable' => 'tblorte',
                               'seldbindex' => 'fldindex',
                               'seldbfield' => 'fldBez',
                               'seldbwhere' => 'fldo01typ="ZIMMER"',
                               'dbfield' => 'fldid_zimmer' ),
                       array ( 'label' => 'Gesuchtes:',
                               'name' => 'gesuchtes', 
                               'width' => 10, 
                               //'type' => 'prozref',
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tblsuchobj',
                               'seldbindex' => 'fldindex',
                               'seldbfield' => 'fldbez',
                               'dbfield' => 'fldid_suchobj' ));


$pararray = array ( 'headline' => 'Möbel',
                    'name' => 'Orte',
                    'dbwhere' => 'fldo01typ="MOEBEL"',
                    'UPDATE' => 'UPDATE tblorte SET fldproz=100 WHERE fldindex=&fldid_zimmer&',
                    'dbtable' => 'tblorte',
                    'fldindex' => 'fldindex');

?>