<?php

$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'Bezeichung',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'Etage',
                             'name' => 'etage',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tbletagen',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_etage' ),
                     array ( 'label' => 'Zimmer',
                             'name' => 'zimmer',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldindex',
                             'seldbwhere' => 'fldo01typ="ZIMMER"',
                             'dbfield' => 'fldid_zimmer' ),
                     array ( 'label' => 'Anzeigen',
                             'name' => 'anzeigen',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldview' ),
                     array ( 'label' => 'X-Koor',
                             'name' => 'xkoor',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldxkoor' ),
                     array ( 'label' => 'Y-Koor',
                             'name' => 'ykoor',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldykoor' ),
                     array ( 'label' => 'Breite',
                             'name' => 'breite',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldbreite' ),
                     array ( 'label' => 'Höhe',
                             'name' => 'hoehe',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldhoehe' ),
                     array ( 'label' => 'Typ',
                             'name' => 'Typ',
                             'default' => 'MOEBEL',
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldo01typ' ));

$filterarray = array ( array ( 'label' => 'Etage:',
                               'name' => 'etage', 
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tbletagen',
                               'seldbindex' => 'fldindex',
                               'seldbfield' => 'fldbez',
                               'dbfield' => 'fldid_etage' ));


$pararray = array ( 'headline' => 'Möbel',
                    'name' => 'Orte',
                    'dbwhere' => 'fldo01typ="MOEBEL"',
                    'dbtable' => 'tblorte',
                    'fldindex' => 'fldindex');

?>