<?php

$listarray = array ( 
                     array ( 'label' => 'Nr',
                             'width' => 10, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'Bezeichung',
                             'width' => 200, 
                             'grafiklink' => 'J',
                             'grafiketageid' => 'fldid_etage',
                             'grafikurl' => 'roomgrafik.php',
                             'roomtyp' => 'ZIMMER',
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'Kurz',
                             'name' => 'kurz',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldkurz' ),
//                     array ( 'label' => 'Etage',
//                             'name' => 'etage',
//                             'width' => 20, 
//                             'type' => 'selectid',
//                             'dbtable' => 'tbletagen',
//                             'seldbfield' => 'fldbez',
//                             'seldbindex' => 'fldindex',
//                             'dbfield' => 'fldid_etage' ),
                     array ( 'label' => 'Etage',
                             'name' => 'etage',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldindex',
                             'seldbwhere' => 'fldo01typ="ETAGEN"',
                             'dbfield' => 'fldid_ort' ),
                     array ( 'label' => 'Anzeigen',
                             'name' => 'anzeigen',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldview' ),
                     array ( 'label' => 'X-Koor',
                             'name' => 'xkoor',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldxkoor' ),
                     array ( 'label' => 'Y-Koor',
                             'name' => 'ykoor',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldykoor' ),
                     array ( 'label' => 'Breite',
                             'name' => 'breite',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldbreite' ),
                     array ( 'label' => 'Höhe',
                             'name' => 'hoehe',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldhoehe' ),
                     array ( 'label' => 'Prozent',
                             'name' => 'proz',
                             'width' => 200, 
                             'type' => 'prozref',
                             'roomid' => 'fldid_orte',
                             'dbfield' => 'fldproz' ),
                     array ( 'label' => 'Typ',
                             'name' => 'Typ',
                             'default' => 'ZIMMER',
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldo01typ' ),
                     array ( 'label' => 'E',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'showtab.php?menu=etagen',
                             'dbfield' => 'icon-book' ),
                     array ( 'label' => 'M',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'showtab.php?menu=moebel',
                             'dbfield' => 'icon-book' ));

//$filterarray = array ( array ( 'label' => 'Etage:',
//                               'name' => 'etage', 
//                               'width' => 10, 
//                               'type' => 'selectid',
//                               'sign' => '=',
//                               'dbtable' => 'tbletagen',
//                               'seldbindex' => 'fldindex',
//                               'seldbfield' => 'fldbez',
//                               'dbfield' => 'fldid_etage' ));
$filterarray = array ( array ( 'label' => 'Etage:',
                               'name' => 'etage', 
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tblorte',
                               'seldbindex' => 'fldindex',
                               'seldbfield' => 'fldBez',
                               'seldbwhere' => 'fldo01typ="ETAGEN"',
                               'dbfield' => 'fldid_etage' ));


$pararray = array ( 'headline' => 'Zimmer',
                    'name' => 'Orte',
                    'dbwhere' => 'fldo01typ="ZIMMER"',
                    'orderby' => 'fldkurz',
                    'dbtable' => 'tblorte',
                    'fldindex' => 'fldindex');

?>